apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
    name: rest-api-test
    projectName: Default Project
    annotations:
        componentType: service
spec:
    build:
        branch: main
    inbound:
        - name: rest-api-test
          port: 8080
          type: REST
          visibility: Public
          context: /
