apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
    name: todo-server
    projectName: Default Project
    annotations:
        componentType: service
spec:
    build:
        branch: main
    inbound:
        - name: todo-server
          port: 5000
          type: REST
          visibility: Public
          context: /
