apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
    name: test-server1
    projectName: "Demo Project"
    annotations:
        componentType: service
spec:
    build:
        branch: main
    inbound:
        - name: test-server1
          port: 5000
          type: REST
          visibility: Public
          context: /
